name: CI-Develop

on:
  pull_request:
    branches: [ develop ]
    types: [closed] # Solo cuando el PR se cierra

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Firebase CLI
        run: |
          yarn add -g firebase-tools

      - name: Install Dependencies
        run: yarn install

      - name: Build Angular Project (DEV)
        run: yarn run build -- --configuration=test

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project colegio-monte-verde-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
